name: Inaccurate information report
description: Report an inaccurate entry.
title: "[Inaccurate] <The name of the offending job position>"
labels: Inaccuracy

body:
- type: markdown
  attributes:
    value: |
      Thank you for taking the time to file a bug report. Before you create a new issue please do the following:
      - Check the issue section to see if there is already an issue discussing your problem.

- type: textarea
  attributes:
    label: "Paste the offending README section (entire row):"
  validations:
    required: true

- type: textarea
  attributes:
    label: "Explain which part of the listing is inaccurate:"
  validations:
    required: true